# Generated by Django 4.1 on 2022-08-24 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0004_document_alter_post_mainphoto'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='image_converted',
            field=models.ImageField(null=True, upload_to='result_files/'),
        ),
    ]
