# Generated by Django 4.1 on 2022-08-24 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0005_document_image_converted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='uploadedFile',
            field=models.FileField(upload_to='Uploaded_Files/'),
        ),
    ]
